### ISSUE TITLE
Button Widths not matching width settings

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-TerminalCommandsExtended#21]
Button widths are still depending on the text in the button, rather than the spacing set via the Width parameter in the button definition.

![CR-10 v2 (Yellow) LAN  OctoPrint  2020-11-23 14-37-43](https://user-images.githubusercontent.com/57936294/100024765-445c9b80-2d9c-11eb-9ab1-634755ae918f.jpg)

They should be taking up the number of columns that they are defined as, with the text/icon centered in the button.

Mac OSX 15.5.7, Firefox and Safari, OctoPrint 1.4.2, TCE v0.1.6, Python v2.7.16 (no, I haven't updated, as 3.x broke a bunch of favorite plugins and I downgraded)

**Comment by KenLucke** [comment]
```
     terminalcommandsextended:
        _config_version: 4
        commands:
        -   command: 'G28

                G1 X0 Y0 Z0'
            confirmation: true
            enabled_while_printing: false
            icon: fas fa-home
            input: []
            label: Home Print Head
            message: You are about to initated a Print Head Home to 0,0,0
            offset: '0'
            tooltip: Home Print Head to 0,0,0
            width: '6'
        -   command: 'G28

                G29 T S35000'
            confirmation: true
            enabled_while_printing: false
            icon: fas fa-bed
            input: []
            label: Bed Level
            message: You are about to initated a Bed Level Probe Sequence
            offset: '0'
            tooltip: Level Bed with BLToucch Probe
            width: '6'
        -   command: M290 Z0.10 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-angle-up
            input: []
            label: Babystep Z +0.10
            message: ''
            offset: '0'
            tooltip: Babystep Z +0.1
            width: '4'
        -   command: M290 Z0.25 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-angle-double-up
            input: []
            label: Babystep Z +0.25
            message: ''
            offset: '0'
            tooltip: Babystep Z +0.25
            width: '4'
        -   command: M290 Z0.50 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-long-arrow-alt-up
            input: []
            label: Babystep Z +0.50
            message: ''
            offset: 0
            tooltip: Babystep Z +0.5
            width: '4'
        -   command: M290 Z0.75 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-arrow-up
            input: []
            label: Babystep Z +0.75
            message: ''
            offset: '2'
            tooltip: Babystep Z +0.75
            width: '4'
        -   command: M290 Z 1.0 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-arrow-circle-up
            input: []
            label: Babystep Z +1.00
            message: ''
            offset: '0'
            tooltip: Babystep Z +1.0
            width: '4'
        -   command: M290 Z-0.10 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-angle-down
            input: []
            label: Babystep Z -0.10
            message: ''
            offset: '0'
            tooltip: Babystep Z -0.1
            width: '4'
        -   command: M290 Z-0.25 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-angle-double-down
            input: []
            label: Babystep Z -0.25
            message: ''
            offset: 0
            tooltip: Babystep Z -0.25
            width: '4'
        -   command: M290 Z-0.50 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-long-arrow-alt-down
            input: []
            label: Babystep Z -0.50
            message: ''
            offset: 0
            tooltip: Babystep Z -0.5
            width: '4'
        -   command: M290 Z-0.75 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-arrow-down
            input: []
            label: Babystep Z -0.75
            message: ''
            offset: '2'
            tooltip: Babystep Z -0.75
            width: '4'
        -   command: M290 Z-1.0 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-arrow-circle-down
            input: []
            label: Babystep Z -1.00
            message: ''
            offset: '0'
            tooltip: Babystep Z -1.0
            width: '4'
        -   command: M104 S180
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Nozzle 180°
            message: ''
            offset: '0'
            tooltip: Set Nozzle 180°
            width: '3'
        -   command: M104 S185
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Nozzle 185°
            message: ''
            offset: 0
            tooltip: Set Nozzle 185°
            width: '3'
        -   command: M104 S190
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Nozzle 190°
            message: ''
            offset: 0
            tooltip: Set Nozzle 190°
            width: '3'
        -   command: M104 S195
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Nozzle 195°
            message: ''
            offset: 0
            tooltip: Set Nozzle 195°
            width: '3'
        -   command: M104 S200
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-quarter
            input: []
            label: Set Nozzle 200°
            message: ''
            offset: '0'
            tooltip: Set Nozzle 200°
            width: '3'
        -   command: M104 S205
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-quarter
            input: []
            label: Set Nozzle 205°
            message: ''
            offset: '0'
            tooltip: Set Nozzle 205°
            width: '3'
        -   command: M104 S210
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Nozzle 210°
            message: ''
            offset: 0
            tooltip: Set Nozzle 210°
            width: '3'
        -   command: M104 S215
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Nozzle 215°
            message: ''
            offset: 0
            tooltip: Set Nozzle 215°
            width: '3'
        -   command: M104 S220
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Nozzle 220°
            message: ''
            offset: 0
            tooltip: Set Nozzle 220°
            width: '3'
        -   command: M104 S225
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Nozzle 225°
            message: ''
            offset: 0
            tooltip: Set Nozzle 225°
            width: '3'
        -   command: M104 S230
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Nozzle 230°
            message: ''
            offset: '0'
            tooltip: Set Nozzle 230°
            width: '3'
        -   command: M104 S235
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Nozzle 235°
            message: ''
            offset: 0
            tooltip: Set Nozzle 235°
            width: '3'
        -   command: M104 S240
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Nozzle 240°
            message: ''
            offset: 0
            tooltip: Set Nozzle 240°
            width: '3'
        -   command: M104 S245
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Nozzle 245°
            message: ''
            offset: 0
            tooltip: Set Nozzle 245°
            width: '3'
        -   command: M104 S250
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Nozzle 250°
            message: ''
            offset: 0
            tooltip: Set Nozzle 250°
            width: '3'
        -   command: M104 S255
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Nozzle 255°
            message: ''
            offset: 0
            tooltip: Set Nozzle 255°
            width: '3'
        -   command: M140 S50
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Build Plate 50°
            message: ''
            offset: 0
            tooltip: Set Build Plate 50º
            width: '4'
        -   command: M140 S55
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Build Plate 55°
            message: ''
            offset: 0
            tooltip: Set Build Plate 55°
            width: '4'
        -   command: M140 S60
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-quarter
            input: []
            label: Set Build Plate 60°
            message: ''
            offset: 0
            tooltip: Set Build Plate 60º
            width: '4'
        -   command: M140 S65
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-quarter
            input: []
            label: Set Build Plate 65°
            message: ''
            offset: 0
            tooltip: Set Build Plate 65°
            width: '4'
        -   command: M140 S70
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Build Plate 70°
            message: ''
            offset: 0
            tooltip: Set Build Plate 70º
            width: '4'
        -   command: M140 S75
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Build Plate 75°
            message: ''
            offset: 0
            tooltip: Set Build Plate 75°
            width: '4'
        -   command: M140 S80
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Build Plate 80°
            message: ''
            offset: 0
            tooltip: Set Build Plate 80º
            width: '4'
        -   command: M140 S85
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Build Plate 85°
            message: ''
            offset: 0
            tooltip: Set Build Plate 85°
            width: '4'
        -   command: M140 S90
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Build Plate 90°
            message: ''
            offset: 0
            tooltip: Set Build Plate 90º
            width: '4'
        -   command: M140 S95
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Build Plate 95°
            message: ''
            offset: 0
            tooltip: Set Build Plate 95°
            width: '4'
        -   command: M140 S100
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Build Plate 100°
            message: ''
            offset: 0
            tooltip: Set Build Plate 100°
            width: '4'
        -   command: M140 S110
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Build Plate 110°
            message: ''
            offset: 0
            tooltip: Set Build Plate 110°
            width: '4'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 2
        -   command: M107
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 0%
            message: ''
            offset: '2'
            tooltip: Set Fan Speed 0%
            width: '4'
        -   command: M106 S25
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 10%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 10%
            width: '4'
        -   command: M106 S64
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 25%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 25%
            width: '4'
        -   command: M106 S85
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 33%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 33%
            width: '4'
        -   command: M106 S128
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 50%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 50%
            width: '4'
        -   command: M106 S170
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 66%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 66%
            width: '4'
        -   command: M106 S192
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 75%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 75%
            width: '4'
        -   command: M106 S255
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 100%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 100%
            width: '4'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 2
        -   command: M303 E0 S210 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 210°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: '2'
            tooltip: PID Tune Hotend 210°/10 Iterations
            width: '4'
        -   command: M303 E0 S220 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 220°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: 0
            tooltip: PID Tune Hotend 220°/10 Iterations
            width: '4'
        -   command: M303 E0 S230 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 230°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: 0
            tooltip: PID Tune Hotend 230°/10 Iterations
            width: '4'
        -   command: M303 E0 S240 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 240°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: 0
            tooltip: PID Tune Hotend 240°/10 Iterations
            width: '4'
        -   command: M303 E0 S250 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 250°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: 0
            tooltip: PID Tune Hotend 250°/10 Iterations
            width: '4'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 2
        -   command: M303 E-1 S65 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 65°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: '2'
            tooltip: PID Tune Build Plate 65°/10 Iterations
            width: '4'
        -   command: M303 E-1 S75 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 75°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: 0
            tooltip: PID Tune Build Plate 75°/10 Iterations
            width: '4'
        -   command: M303 E-1 S80 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 80°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: '0'
            tooltip: PID Tune Build Plate 80°/10 Iterations
            width: '4'
        -   command: M303 E-1 S90 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 90°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: '0'
            tooltip: PID Tune Build Plate 90°/10 Iterations
            width: '4'
        -   command: M303 E-1 S100 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 100°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: 0
            tooltip: PID Tune Build Plate 100°/10 Iterations
            width: '4'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 2
 ```
