### ISSUE TITLE
[Feature Request] Import/Export of buttons

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-TerminalCommandsExtended#9]
I would love to be able to export the buttons to a CSV file or similar, to be able to back them up independently of the main OP backup, and to be able to import them into another instance of OP running on another machine without having to individually enter all the same buttons all over again.  It would also enable creating/editing/sorting the buttons in the CSV file instead of the plugin interface.

**Comment by EagleB3** [comment]
@jneilliii , Can you please tell me which file the plugin currently stores information about the created buttons in?
So that you can back up your settings.

I think it would be useful to add this information to the plugin's README.md file.

**Comment by jneilliii** [comment]
All configurations are stored in config.yaml and as such, the standard OctoPrint Backup Plugin will back those up.

**Comment by EagleB3** [comment]
@jneilliii , This is very reasonable and very convenient.
Thank!

**Comment by Jon-So** [comment]
following!

**Comment by Jon-So** [comment]
anybody have a good list of commands and willing to share them?

**Comment by KenLucke** [comment]
> anybody have a good list of commands and willing to share them?

<img width="880" alt="image" src="https://user-images.githubusercontent.com/57936294/100814671-0fcd8d00-33f7-11eb-8f7e-30cd8a8105ff.png">

```
    terminalcommandsextended:
        _config_version: 4
        commands:
        -   command: 'G28
            G1 X0 Y0 Z0'
            confirmation: true
            enabled_while_printing: false
            icon: fas fa-home
            input: []
            label: Home Print Head
            message: You are about to initiate a Print Head Home to 0,0,0
            offset: '0'
            tooltip: Home Print Head to 0,0,0
            width: '6'
        -   command: 'G28
            G29 T S35000'
            confirmation: true
            enabled_while_printing: false
            icon: fas fa-bed
            input: []
            label: Bed Level
            message: You are about to imitated a Bed Level Probe Sequence
            offset: '0'
            tooltip: Level Bed with BLTouch Probe
            width: '6'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: M290 Z0.10 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-angle-up
            input: []
            label: Babystep Z +0.10
            message: ''
            offset: '1'
            tooltip: Babystep Z +0.1
            width: '2'
        -   command: M290 Z0.25 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-angle-double-up
            input: []
            label: Babystep Z +0.25
            message: ''
            offset: '0'
            tooltip: Babystep Z +0.25
            width: '2'
        -   command: M290 Z0.50 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-long-arrow-alt-up
            input: []
            label: Babystep Z +0.50
            message: ''
            offset: 0
            tooltip: Babystep Z +0.5
            width: '2'
        -   command: M290 Z0.75 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-arrow-up
            input: []
            label: Babystep Z +0.75
            message: ''
            offset: '0'
            tooltip: Babystep Z +0.75
            width: '2'
        -   command: M290 Z 1.0 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-arrow-circle-up
            input: []
            label: Babystep Z +1.00
            message: ''
            offset: '0'
            tooltip: Babystep Z +1.0
            width: '2'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: M290 Z-0.10 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-angle-down
            input: []
            label: Babystep Z -0.10
            message: ''
            offset: '1'
            tooltip: Babystep Z -0.1
            width: '2'
        -   command: M290 Z-0.25 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-angle-double-down
            input: []
            label: Babystep Z -0.25
            message: ''
            offset: 0
            tooltip: Babystep Z -0.25
            width: '2'
        -   command: M290 Z-0.50 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-long-arrow-alt-down
            input: []
            label: Babystep Z -0.50
            message: ''
            offset: 0
            tooltip: Babystep Z -0.5
            width: '2'
        -   command: M290 Z-0.75 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-arrow-down
            input: []
            label: Babystep Z -0.75
            message: ''
            offset: '0'
            tooltip: Babystep Z -0.75
            width: '2'
        -   command: M290 Z-1.0 P0
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-arrow-circle-down
            input: []
            label: Babystep Z -1.00
            message: ''
            offset: '0'
            tooltip: Babystep Z -1.0
            width: '2'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: M104 S180
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Nozzle 180°
            message: ''
            offset: '0'
            tooltip: Set Nozzle 180°
            width: '3'
        -   command: M104 S185
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Nozzle 185°
            message: ''
            offset: 0
            tooltip: Set Nozzle 185°
            width: '3'
        -   command: M104 S190
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Nozzle 190°
            message: ''
            offset: 0
            tooltip: Set Nozzle 190°
            width: '3'
        -   command: M104 S195
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Nozzle 195°
            message: ''
            offset: 0
            tooltip: Set Nozzle 195°
            width: '3'
        -   command: M104 S200
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-quarter
            input: []
            label: Set Nozzle 200°
            message: ''
            offset: '0'
            tooltip: Set Nozzle 200°
            width: '3'
        -   command: M104 S205
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-quarter
            input: []
            label: Set Nozzle 205°
            message: ''
            offset: '0'
            tooltip: Set Nozzle 205°
            width: '3'
        -   command: M104 S210
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Nozzle 210°
            message: ''
            offset: 0
            tooltip: Set Nozzle 210°
            width: '3'
        -   command: M104 S215
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Nozzle 215°
            message: ''
            offset: 0
            tooltip: Set Nozzle 215°
            width: '3'
        -   command: M104 S220
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Nozzle 220°
            message: ''
            offset: 0
            tooltip: Set Nozzle 220°
            width: '3'
        -   command: M104 S225
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Nozzle 225°
            message: ''
            offset: 0
            tooltip: Set Nozzle 225°
            width: '3'
        -   command: M104 S230
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Nozzle 230°
            message: ''
            offset: '0'
            tooltip: Set Nozzle 230°
            width: '3'
        -   command: M104 S235
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Nozzle 235°
            message: ''
            offset: 0
            tooltip: Set Nozzle 235°
            width: '3'
        -   command: M104 S240
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Nozzle 240°
            message: ''
            offset: 0
            tooltip: Set Nozzle 240°
            width: '3'
        -   command: M104 S245
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Nozzle 245°
            message: ''
            offset: 0
            tooltip: Set Nozzle 245°
            width: '3'
        -   command: M104 S250
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Nozzle 250°
            message: ''
            offset: 0
            tooltip: Set Nozzle 250°
            width: '3'
        -   command: M104 S255
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Nozzle 255°
            message: ''
            offset: 0
            tooltip: Set Nozzle 255°
            width: '3'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: M140 S50
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Build Plate 50°
            message: ''
            offset: '0'
            tooltip: Set Build Plate 50º
            width: '3'
        -   command: M140 S55
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-empty
            input: []
            label: Set Build Plate 55°
            message: ''
            offset: 0
            tooltip: Set Build Plate 55°
            width: '3'
        -   command: M140 S60
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-quarter
            input: []
            label: Set Build Plate 60°
            message: ''
            offset: 0
            tooltip: Set Build Plate 60º
            width: '3'
        -   command: M140 S65
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-quarter
            input: []
            label: Set Build Plate 65°
            message: ''
            offset: '0'
            tooltip: Set Build Plate 65°
            width: '3'
        -   command: M140 S70
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Build Plate 70°
            message: ''
            offset: 0
            tooltip: Set Build Plate 70º
            width: '3'
        -   command: M140 S75
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-half
            input: []
            label: Set Build Plate 75°
            message: ''
            offset: 0
            tooltip: Set Build Plate 75°
            width: '3'
        -   command: M140 S80
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Build Plate 80°
            message: ''
            offset: 0
            tooltip: Set Build Plate 80º
            width: '3'
        -   command: M140 S85
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-three-quarters
            input: []
            label: Set Build Plate 85°
            message: ''
            offset: 0
            tooltip: Set Build Plate 85°
            width: '3'
        -   command: M140 S90
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Build Plate 90°
            message: ''
            offset: 0
            tooltip: Set Build Plate 90º
            width: '3'
        -   command: M140 S95
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Build Plate 95°
            message: ''
            offset: 0
            tooltip: Set Build Plate 95°
            width: '3'
        -   command: M140 S100
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Build Plate 100°
            message: ''
            offset: 0
            tooltip: Set Build Plate 100°
            width: '3'
        -   command: M140 S110
            confirmation: false
            enabled_while_printing: true
            icon: fas fa-thermometer-full
            input: []
            label: Set Build Plate 110°
            message: ''
            offset: 0
            tooltip: Set Build Plate 110°
            width: '3'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: M107
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 0%
            message: ''
            offset: '0'
            tooltip: Set Fan Speed 0%
            width: '3'
        -   command: M106 S25
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 10%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 10%
            width: '3'
        -   command: M106 S64
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 25%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 25%
            width: '3'
        -   command: M106 S85
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 33%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 33%
            width: '3'
        -   command: M106 S128
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 50%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 50%
            width: '3'
        -   command: M106 S170
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 66%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 66%
            width: '3'
        -   command: M106 S192
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 75%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 75%
            width: '3'
        -   command: M106 S255
            confirmation: false
            enabled_while_printing: true
            icon: fab fa-chrome
            input: []
            label: Set Fan Speed 100%
            message: ''
            offset: 0
            tooltip: Set Fan Speed 100%
            width: '3'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: M303 E0 S210 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 210°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: '1'
            tooltip: PID Tune Hotend 210°/10 Iterations
            width: '2'
        -   command: M303 E0 S220 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 220°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: 0
            tooltip: PID Tune Hotend 220°/10 Iterations
            width: '2'
        -   command: M303 E0 S230 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 230°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: 0
            tooltip: PID Tune Hotend 230°/10 Iterations
            width: '2'
        -   command: M303 E0 S240 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 240°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: 0
            tooltip: PID Tune Hotend 240°/10 Iterations
            width: '2'
        -   command: M303 E0 S250 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Hotend 250°/10
            message: Are you sure that you wish to PID Tune the Hotend Now?
            offset: 0
            tooltip: PID Tune Hotend 250°/10 Iterations
            width: '2'
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: ''
            confirmation: false
            enabled_while_printing: false
            icon: fas fa-gear
            input: []
            label: <BR>
            message: ''
            offset: 0
            tooltip: ''
            width: 12
        -   command: M303 E-1 S65 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 65°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: '1'
            tooltip: PID Tune Build Plate 65°/10 Iterations
            width: '2'
        -   command: M303 E-1 S75 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 75°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: 0
            tooltip: PID Tune Build Plate 75°/10 Iterations
            width: '2'
        -   command: M303 E-1 S80 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 80°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: '0'
            tooltip: PID Tune Build Plate 80°/10 Iterations
            width: '2'
        -   command: M303 E-1 S90 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 90°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: '0'
            tooltip: PID Tune Build Plate 90°/10 Iterations
            width: '2'
        -   command: M303 E-1 S100 C10
            confirmation: true
            enabled_while_printing: false
            icon: fab fa-hotjar
            input: []
            label: PID Tune Bed 100°/10
            message: Are you sure that you wish to PID Tune the Buildplate Now?
            offset: 0
            tooltip: PID Tune Build Plate 100°/10 Iterations
            width: '2'

```
